name: Desplegar PHP en Apache

on:
  push:
    branches:
      - master  # Cambiar a la rama que desees desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Configurar claves SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 700 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      
    - name: Desplegar en ECS de Huawei Cloud
      run: |
        # Coloca aquí los comandos para desplegar tu aplicación en el ECS
        # Por ejemplo, puedes utilizar SCP o rsync para copiar los archivos al servidor
        # Luego puedes usar SSH para ejecutar comandos en el servidor, como iniciar la aplicación.          
           cd /home/runner/work/
           git pull origin master  # Actualiza el repositorio con el código más reciente  
           scp -p /home/runner/work/phpTest/index.php ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/var/www/html
           
    env:
      SSH_PRIVATE_KEY: ${{ secrets.TEST_SSH_KEY }}
